In [9]:
import numpy as np
num_array = np.arange(5)
num_array

array([0, 1, 2, 3, 4])

In [10]:
num_array*4


array([ 0,  4,  8, 12, 16])

In [11]:
num_array = np.random.randn(4, 3)
num_array.mean(0)


array([-0.02594968,  0.47690411, -1.58030787])

In [12]:
dm = num_array - num_array.mean(0)
print(dm)
print(dm.mean(0))


[[-1.00654046 -0.10685371 -0.01737452]
 [-0.43075023 -1.39308271 -0.02642014]
 [ 1.98620411  1.15551005  0.88132547]
 [-0.54891342  0.34442637 -0.8375308 ]]
[2.77555756e-17 1.38777878e-17 5.55111512e-17]


In [14]:
r_means = num_array.mean(1)
print(r_means.shape)
print(r_means.reshape((4, 1)))
dm = num_array-r_means.reshape((4,1))
print(dm.mean(1))


(4,)
[[-0.75337404]
 [-0.99320217]
 [ 0.96456207]
 [-0.72379043]]
[0.00000000e+00 7.40148683e-17 7.40148683e-17 0.00000000e+00]


In [21]:
zero_array = np.zeros((4,4))
array_3d = zero_array[:,np.newaxis,:]
array_3d.shape

(4, 1, 4)

In [22]:
arr_1d = np.random.normal(size=3)
arr_1d[:,np.newaxis]


array([[-1.42492468],
       [ 0.3630849 ],
       [ 0.83401657]])

In [23]:
arr_1d[np.newaxis,:]

array([[-1.42492468,  0.3630849 ,  0.83401657]])

In [25]:
array = np.random.randn(3,4,5)
depth_means = array.mean(2)
print(depth_means)
print(depth_means.shape)


[[-0.07067201 -0.55497039 -0.36749818  0.54732977]
 [-0.64488794 -0.77168945  0.31604643 -0.84397932]
 [-0.41777185  0.36606447 -0.45710466 -0.37478846]]
(3, 4)


In [26]:
new_arr = np.zeros((4,3))
new_arr[:] = 5
print(new_arr)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [36]:
print('Setting Array Values By Broadcasting')
column = np.array([1.28,-0.42,0.44,1.6])
new_arr[:4] = column[:,np.newaxis]
print(new_arr)
new_arr[:2] = [[-2],[-5]]
print(new_arr)
new_arr[:3] = [[3],[4],[6]]
print(new_arr)

Setting Array Values By Broadcasting
[[ 1.28  1.28  1.28]
 [-0.42 -0.42 -0.42]
 [ 0.44  0.44  0.44]
 [ 1.6   1.6   1.6 ]]
[[-2.   -2.   -2.  ]
 [-5.   -5.   -5.  ]
 [ 0.44  0.44  0.44]
 [ 1.6   1.6   1.6 ]]
[[3.  3.  3. ]
 [4.  4.  4. ]
 [6.  6.  6. ]
 [1.6 1.6 1.6]]
