In [26]:
import numpy as np
data1 = [2,3,4,5,6,7]
array_1d = np.array(data1)
print(array_1d)



[2 3 4 5 6 7]


In [30]:
data_1 = [[1,2,5,8,9],[34,12,14,6,7]]
data_2 = [[2,4,5,6,7],[2,3,4,56,3]]
array_2d_1 = np.array(data_1)
array_2d_2 = np.array(data_2)
print("2d Array 1: ",array_2d_1)
print('2d Array 2: ',array_2d_2)
array_multiplication= array_2d_1*array_2d_2
print('Multiplication of Arrays: ',array_multiplication)
array_addition = array_2d_1+array_2d_2
print('Addition of Arrays: ',array_addition)
array_subtract = array_2d_2-array_2d_1
print('Subtraction of Arrays: ',array_subtract)
array_2d_1_division = 1/array_2d_1
print('Reciprocal of array 1: ',array_2d_1_division)
array_2d_1>array_2d_2


2d Array 1:  [[ 1  2  5  8  9]
 [34 12 14  6  7]]
2d Array 2:  [[ 2  4  5  6  7]
 [ 2  3  4 56  3]]
Multiplication of Arrays:  [[  2   8  25  48  63]
 [ 68  36  56 336  21]]
Addition of Arrays:  [[ 3  6 10 14 16]
 [36 15 18 62 10]]
Subtraction of Arrays:  [[  1   2   0  -2  -2]
 [-32  -9 -10  50  -4]]
Reciprocal of array 1:  [[1.         0.5        0.2        0.125      0.11111111]
 [0.02941176 0.08333333 0.07142857 0.16666667 0.14285714]]


array([[False, False, False,  True,  True],
       [ True,  True,  True, False,  True]])